- job:
   name: 'configure_auto_test'
   description: 'Auto configure Jenkins Job to perform automated tests'
   project-type: freestyle
   block-downstream: false
   auth-token: slave
   parameters:
      - node:
          name: List of connected nodes
          type: multi-select
          ignore-offline-nodes: true
          allowed-multiselect: false
#     - choice:
#         name: Device
#         description: List of available devices
#         choices:
#           - Samsung
#           - Oppo
#           - HTC
      - extended-choice:
          name: Device
          description: "Available options"
          type: single-select
          value: Samsung,Oppo,HTC
      - reactive_choice:
          name: Slaves
          script: |
              if(Device.equals("Samsung")){ return['nandu','manikanta'] } else if(Device.equals("Oppo")) { return['nikhil','manikanta']} else if(Device.equals("HTC")) {return['nandu','nikhil']} else{return ("Select an item")}
          projectName: Test_Automation
          description: Available Node
          type: multi-select
           #allowed-multiselect: true
          referencedParameters: Device
#          value: nandu,nikhil,manikanta,ravichandra

   builders:
     - shell: python jenkins_file.py $Device $Slaves
   scm:
     - git:
          url: https://github.com/OSrivalli/jobs
          credentials:
            - name: srivalli
          branches:
            - '*/master'
          skip-tag: true

- project:
    name: Test_Automation
    jobs:
      - configure_auto_test

